[package]
name = "firmware"
version = "0.1.0"
edition = "2021"

[features]


[dependencies]
atsamd-hal = { workspace = true, features = [
    "same54p-rt",
    "can",
    "usb",
    "async",
    "rtic",
] }
bsp = { path = "../bsp" }
diag_common = { path = "../diag_common", features = ["mcu"] }
cortex-m = { workspace = true, features = ["inline-asm"] }
cortex-m-rt.workspace = true
mcan.workspace = true

packed_struct = { version = "0.10.1", default-features = false }
bitfield-struct = "0.9.5"
usbd-serial = "0.2.2"
automotive_diag = { version = "0.1.21", default-features = false, features = [
    "kwp2000",
] }
rtic-sync = "1.4.0"

# Format and printing to SWD
defmt = "1.0.1"
defmt-rtt = "1.0.0"

# RTIC
num-traits = { version = "0.2.19", default-features = false }
bitvec = { version = "1.0.1", default-features = false }
rtic = { version = "2.2.0", features = ["thumbv7-backend"] }
heapless = "0.9.1"
static_cell = "2.1.1"

futures = { version = "0.3.31", default-features = false }

[build-dependencies]
candb_codegen = { path = "../candb_codegen" }
chrono = { version = "0.4", default-features = false, features = ["now"] }
rustc_version = "0.4.1"

[profile.dev]
incremental = false
debug = true
lto = true

[profile.release]
debug = true
#strip="symbols"
lto = "fat"
opt-level = 3
codegen-units = 1
#panic="abort"

# For cargo flash
[package.metadata]
chip = "ATSAME54P20A"
